### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [jwtowner/lug#5]
I would like to point out that identifiers like “[`LUG_HPP__`](https://github.com/jwtowner/lug/blob/490ee5e9df76c963b47752b78e7df697f5f8d5f0/lug/lug.hpp#L5 "Update candidate")” and “[`LUG_DETAIL_HPP__`](https://github.com/jwtowner/lug/blob/1820fe72ba4f2361bbe884fd6f500c7d661cac79/lug/detail.hpp#L5 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jwtowner** [comment]
Fixed this in 3a412de84cefcebbc37922e7fc1a39cc00054cc3 thanks.

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/jwtowner/lug/commit/3a412de84cefcebbc37922e7fc1a39cc00054cc3 "Remove double underscores from include guards.").
