### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [jwtowner/lug#7]
:thought_balloon: I find that an include guard like “[`LUG_HPP`](https://github.com/jwtowner/lug/blob/3a412de84cefcebbc37922e7fc1a39cc00054cc3/lug/lug.hpp#L5 "Update candidate")” is too short for the safe reuse of your header file (when it belongs to an application programming interface).

**Comment by jwtowner** [comment]
Good point, I can fix that. Will add a `LUG_INCLUDE_` prefix, causing the general pattern to change to `LUG_INCLUDE_<directory>_<filename>`. So `LUG_HPP` will be changed to `LUG_INCLUDE_LUG_LUG_HPP`, `LUG_DETAIL_HPP` will become `LUG_INCLUDE_LUG_DETAIL_HPP`, etc.

It's overly verbose perhaps, but that's probably a good thing here.

**Comment by jwtowner** [comment]
Fixed in commit 9037c0ddaa45b5dc7a4d018f4fb9471f4eea1e6a.

**Comment by elfring** [comment]
Thanks for [another adjustment of include guards](https://github.com/jwtowner/lug/commit/9037c0ddaa45b5dc7a4d018f4fb9471f4eea1e6a "Make header include guards longer").

-----

:thought_balloon: I propose to [reduce the probability for undesirable naming conflicts](https://en.wikipedia.org/wiki/Include_guard#Difficulties "Using a coherent naming scheme?") another bit.

* :thinking: How do you think about to replace the text “INCLUDE_LUG” by [a kind of UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier "Description for the usage of universally unique identifiers")?
:crystal_ball: Will [the collaboration with C++ modules](https://en.cppreference.com/w/cpp/language/modules "Documentation") become more attractive accordingly?

**Comment by jwtowner** [comment]
I think using UUIDs is a little overkill for a toy project like this. There's plenty of more serious C/C++ projects out in the wild (LLVM for example) with header include guards like the ones found here.

I will definitely explore using modules when updating to C++23, but it might make sense to keep this header only and import them as header units. Will have to see how it plays out.

Thanks for the feedback.

**Comment by elfring** [comment]
>I think using UUIDs is a little overkill for a toy project like this.

:thought_balloon: I hope that this evolving software can be taken also a bit more serious for the development of further tools.
